apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cni-plugins.yaml
  - metrics-server.yaml
  - multus.yaml
  - rdma-device-plugin.yaml
  - whereabouts.yaml
